name: Update the directory assets

on:
  push:
    branches:
      - main
    paths:
      - '.wordpress-org/**'
      - 'readme.txt'

jobs:
  assets:
    name: Push assets and readme to trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: unicode-email-addresses
